### ISSUE TITLE
Most classes are not really immutable

### ISSUE THREAD

**Issue by tkrille** [osiam/scim-schema#126]
AFAIK all SCIM-based objects should be immutable, but that's not the case. For instance, we're directly returning the backing collections for all multi-valued attributes and when setting collections via the builders, they're not copied, but used as-is. We should always return unmodifiable views of collections and make defensive copies of collection arguments fed into the builders.

**Comment by tkrille** [comment]
Is this resolved now?

**Comment by tkrille** [comment]
@wallner @fwilhe @dacrome

**Comment by fwilhe** [comment]
This issue was resolved by pr #167

**Comment by dacrome** [comment]
I guess so, because #167 is merged. In the PR's description is a "closes 167" instead of this issue and this is wrong I think.

**Comment by wallner** [comment]
Yes, that was mistake on my part.
