### ISSUE TITLE
Technical name for groups

### ISSUE THREAD

**Issue by sschum** [osiam/scim-schema#130]
At the moment the scim_group stores only "displayName". In our project we have a need for a technical name. So is it possible to add a new (optional) property "name" for each scim_group?

**Comment by tkrille** [comment]
Hi @sschum,

this is not part of the SCIM 2 API. But SCIM provides extension points either by using "extensions" or custom resource types. Custom resource types have to be implemented in OSIAM, but are globally available then. As not everybody needs your feature, I would refrain from implementing it this way. Using extensions might be the best option for you, but unfortunately OSIAM does not support extensions for groups, yet. So if you need this feature, please create another issue for that.

But, why exactly do you need this? Groups support (like any resource) the `external_id` field. That should be the only thing needed, if you want to identify a group without using the UUID, i.e. give it a human-readable but computer-parseable name.

**Comment by sschum** [comment]
I think the idea with the extensions for groups is better than only one additional field. For us this feature is also useful. 

I thought about the externalId. And i think this is also a way for us. but the extensions are more beautiful. 

We would prefer the solution with the extensions and I will open up a new issue in github.

**Comment by tkrille** [comment]
Question has been answered -> closing issue.
