### ISSUE TITLE
Extensions for groups

### ISSUE THREAD

**Issue by sschum** [osiam/scim-schema#131]
In our project we need to add some attributes to a scim_group. So i think we need extensions for a group. 

See [https://github.com/osiam/scim-schema/issues/130]

**Comment by tkrille** [comment]
Hi @sschum,

this is something OSIAM really needs. Unfortunately, it's not so easy to implement, as it requires some major refactoring of the whole extension handling. At this time, any extension is always bound to a User, without the ability to configure this binding. How soon do you need this feature?

**Comment by sschum** [comment]
Our project owner said we need it until the beginning of next week (10.08.). But i think it is to short. Maybe you can tell me when it can be done :)

**Comment by tkrille** [comment]
haha :)

ok, that's not enough time I think. Hard to say exactly, I didn't looked at the code for some time. Can please talk about this with @tpick @timopick?

**Comment by wallner** [comment]
This is something that has to happen in the server, This is why i created osiam/osiam#152 and close this one.
