### ISSUE TITLE
Migrate from wiki to markdown documentation

### ISSUE THREAD

**Issue by dacrome** [osiam/scim-schema#140]

**Comment by tkrille** [comment]
Apparently, a title is enough for this :)

**Comment by sputnik27** [comment]
No, it is not. What is wrong with gh wiki?

**Comment by dacrome** [comment]
The docs should always in sync with the source code. This is only possible when the docs are part of the source code. Like the [README](README.md) and further documentation as markdown files under /docs like already done in the other repos. The wiki should only be used for test results or something similar.

**Comment by sputnik27** [comment]
All right then. The wiki can be cloned locally using `git clone https://github.com/osiam/scim-schema.wiki.git`, which results in a bunch of markdown files. This should not be too hard to arrange nicely, I think..

**Comment by tkrille** [comment]
But you cant't create a PR for the wiki and furthermore you would have to create 2 PRs: one for the changes and one for the docs. Putting the docs as near as possible to the source code makes it easier to change both at the same time.
