### ISSUE TITLE
Update urn schema URIs

### ISSUE THREAD

**Issue by dacrome** [osiam/scim-schema#141]
The [used URIs](https://github.com/osiam/scim-schema/blob/master/src/main/java/org/osiam/resources/scim/Constants.java#L31) in this repo are not up to date with [the specification defined URIs](https://tools.ietf.org/html/draft-ietf-scim-core-schema-22#section-10.4). This is just one task of the obvious todo of the adjustment to the scim specfication.

**Comment by sputnik27** [comment]
@dacrome Is this solved by #144?

**Comment by tkrille** [comment]
@sputnik27 For me it seems to do that.

**Comment by dacrome** [comment]
Yes, #144 solves it.
